// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xplevmzesixsvljndebh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbGV2bXplc2l4c3Zsam5kZWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzAxMjcsImV4cCI6MjA2NDQ0NjEyN30.OfGqrvG5FH7pXTN3kMHjt_MBGjC91XzWlaSDe1B77sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);